apiVersion: rbac-controller.ggh41th.io/v1alpha1
kind: RBACRule
metadata:
  name: testrule
spec:
  bindings:
  - name: test-binding
    subjects: 
    - kind: ServiceAccount
      name: test-sa
      namespaces:
      - default
    - kind: User
      name: TestUser@rbac.com
      namespaces:
      - default
    roleBindings:
    - role: test-role
      namespaces:
      - default